version: '2'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "9292:9292"
  doc:
    build: .
    command: [bundle,exec,yard,server]
    volumes:
      - .:/usr/src/app
    ports:
      - "8808:8808"